[project]
name = "flet-paypal-payment-example"
version = "1.0.0"
description = "flet-paypal-payment-example"
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.10"
dependencies = [
    "flet-paypal-payment @ file:///home/abdo/flet-paypal-payment",
    "flet",
]

# Docs: https://flet.dev/docs/publish
[tool.flet]
org = "com.mycompany"
product = "flet-paypal-payment-example"
company = "Flet"
copyright = "Copyright (C) 2026 by Flet"

[tool.flet.app]
path = "src"
